### ISSUE TITLE
css styling using "deep" depricated

### ISSUE THREAD

**Issue by gedw99** [bendavis78/paper-date-picker#23]
Am getting this:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

Just a heads up

**Comment by bendavis78** [comment]
Fixed in 1.1.0

**Comment by nicholaswmin** [comment]
Just installed via Bower and still getting this deprecation warning. 
The component version is listed as `1.1.3` in `bower.json`

Any ideas on what's going on?
